### ISSUE TITLE
Where can I find the source code for GCDashboard.jar ?

### ISSUE THREAD

**Issue by Fameing** [taljmars/DroneGCS#6]

**Comment by taljmars** [comment]
https://github.com/taljmars/DroneGCS/tree/master/Console

**Comment by taljmars** [comment]
It will be far more stable in the next couple of weeks

**Comment by Fameing** [comment]
I spent a lot of time and looked through the code and tried to collect. But I lost my luck. Since many libraries are in other repositories.

It can collect all external dependencies "<groupId> com.dronegcs </ groupId> and <groupId> com.generic_tools </ groupId>" in one repository in DroneGCS. 
I can help with this.

Also, I would suggest setting travis-ci for assemblies. And go from version 1.0 to the right three-digit version.

**Comment by Fameing** [comment]
Where is the generation of the artifact ? I can not find.
```
<dependency>
       <GroupId> com.dronedb </ groupId>
       <ArtifactId> GeneratedServerClasses </ artifactId>
       <Version> 1.0 </ version>
</ Dependency>
```

**Comment by taljmars** [comment]
It an old artifact. I've stabilize the branch a bit more.
DroneGCS repository should function well this time.

It a good proposal to unify some repositories.
I've made it because they are being used by other projects and because of a naive perception of repository = project.
Do you have an example that i can learn from?

Please update if it now works for you.

Mind that some features require appropriate hardware (such as 3DR antenna, eazyChip, etc..)

**Comment by Fameing** [comment]
Hi,
I did a lot of refactoring the modules and added support travis-ci.
https://travis-ci.org/Fameing/DroneGCS
https://github.com/Fameing/DroneGCS

I need some more time to complete my changes. After I make a Pull request in your repository.

**Comment by taljmars** [comment]
Thanks Ivan.
Changes were updated
